# Generated by Django 6.0.7 on 2026-08-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfumesize',
            options={'ordering': ['price']},
        ),
    ]
